pug_m_rest_demo:
    resource: "@PugMRestDemoBundle/Controller/"
    type:     annotation
    prefix:   /

customers:
    type:   rest
    resource:   PugM\RestDemoBundle\Controller\CustomerController